# @BelongsProject: FamilyAiButler
# @BelongsPackage: ops.nginx
# @ClassName: nginx.local
# @Author: atluofu
# @CreateTime: 2026Year-05Month-20Day
# @Description: 本机 Nginx 临时运行主配置模板
# @Version: 1.0
worker_processes 1;
error_log ${NGINX_ERROR_LOG} warn;
pid ${NGINX_PID_FILE};

events {
    worker_connections 1024;
}

http {
    ${NGINX_MIME_TYPES_INCLUDE}
    default_type application/octet-stream;
    access_log ${NGINX_ACCESS_LOG};
    sendfile on;
    include ${NGINX_SERVER_CONF};
}
