package top.egon.familyaibutler.codegen.ddl;

import org.junit.jupiter.api.Test;
import top.egon.familyaibutler.codegen.schema.ConstraintType;
import top.egon.familyaibutler.codegen.schema.PgColumnModel;
import top.egon.familyaibutler.codegen.schema.PgSchemaModel;
import top.egon.familyaibutler.codegen.schema.PgTableModel;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * @BelongsProject: familyaibutler
 * @BelongsPackage: top.egon.familyaibutler.codegen.ddl
 * @ClassName: PureParseSchemaReaderTest
 * @Author: atluofu
 * @CreateTime: 2026-05-19 00:00
 * @Description: PostgreSQL DDL 纯解析模式测试
 * @Version: 1.0
 */
class PureParseSchemaReaderTest {

    /**
     * 解析订单 DDL 并校验枚举、字段、约束、注释和索引信息。
     */
    @Test
    void shouldParseCommonPostgresqlDdlElements() {
        String ddl = """
                CREATE TYPE order_status AS ENUM ('CREATED', 'PAID', 'CANCELED');
                CREATE TABLE trade_order
                (
                    id           bigserial PRIMARY KEY,
                    order_no     varchar(64)    NOT NULL,
                    buyer_id     bigint         NOT NULL,
                    status       order_status   NOT NULL DEFAULT 'CREATED',
                    total_amount numeric(18, 2) NOT NULL,
                    deleted      boolean        NOT NULL DEFAULT false,
                    version      integer        NOT NULL DEFAULT 0,
                    created_at   timestamptz    NOT NULL DEFAULT now(),
                    CONSTRAINT uk_trade_order_order_no UNIQUE (order_no),
                    CONSTRAINT ck_trade_order_status CHECK (status IN ('CREATED', 'PAID', 'CANCELED'))
                );
                COMMENT ON TABLE trade_order IS 'aggregate=Order;module=trade';
                COMMENT ON COLUMN trade_order.order_no IS '订单号;vo=OrderNo;businessKey=true';
                CREATE INDEX idx_trade_order_buyer_status ON trade_order (buyer_id, status);
                """;

        PgSchemaModel schemaModel = new PureParseSchemaReader().read("public", List.of(ddl));

        assertThat(schemaModel.getEnums()).singleElement()
                .satisfies(pgEnumModel -> {
                    assertThat(pgEnumModel.getTypeName()).isEqualTo("order_status");
                    assertThat(pgEnumModel.getValues()).containsExactly("CREATED", "PAID", "CANCELED");
                });
        PgTableModel tableModel = schemaModel.getTable("trade_order").orElseThrow();
        assertThat(tableModel.getTableComment()).isEqualTo("aggregate=Order;module=trade");
        assertThat(tableModel.getConstraints()).anySatisfy(constraint -> {
            assertThat(constraint.getType()).isEqualTo(ConstraintType.UNIQUE);
            assertThat(constraint.getColumns()).containsExactly("order_no");
        });
        assertThat(tableModel.getIndexes()).singleElement()
                .satisfies(index -> assertThat(index.getColumns()).containsExactly("buyer_id", "status"));
        PgColumnModel orderNo = tableModel.getColumn("order_no").orElseThrow();
        assertThat(orderNo.getLength()).isEqualTo(64);
        assertThat(orderNo.getColumnComment()).contains("vo=OrderNo");
        assertThat(orderNo.isNullable()).isFalse();
    }

    /**
     * 解析 ALTER TABLE、identity 主键和唯一索引等 v0.1 支持范围内的 DDL。
     */
    @Test
    void shouldParseAlterTableIdentityAndUniqueIndex() {
        String ddl = """
                CREATE TABLE trade_order
                (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                );
                ALTER TABLE trade_order ADD COLUMN order_no varchar(64) NOT NULL;
                ALTER TABLE trade_order ADD CONSTRAINT uk_trade_order_order_no UNIQUE (order_no);
                CREATE UNIQUE INDEX idx_trade_order_order_no ON trade_order (order_no);
                """;

        PgSchemaModel schemaModel = new PureParseSchemaReader().read("public", List.of(ddl));

        PgTableModel tableModel = schemaModel.getTable("trade_order").orElseThrow();
        PgColumnModel id = tableModel.getColumn("id").orElseThrow();
        PgColumnModel orderNo = tableModel.getColumn("order_no").orElseThrow();
        assertThat(id.isPrimaryKey()).isTrue();
        assertThat(id.isIdentity()).isTrue();
        assertThat(orderNo.isUnique()).isTrue();
        assertThat(tableModel.getIndexes()).singleElement()
                .satisfies(index -> {
                    assertThat(index.isUnique()).isTrue();
                    assertThat(index.getColumns()).containsExactly("order_no");
                });
    }
}
