# @BelongsProject: FamilyAiButler
# @BelongsPackage: ops.k8s.overlays.dev
# @ClassName: replica-patch
# @Author: atluofu
# @CreateTime: 2026Year-05Month-19Day
# @Description: dev 环境副本数配置
# @Version: 1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-gateway
spec:
  replicas: 1
