# @BelongsProject: FamilyAiButler
# @BelongsPackage: ops.k8s.base
# @ClassName: secret.example
# @Author: atluofu
# @CreateTime: 2026Year-05Month-19Day
# @Description: Kubernetes Secret 样例
# @Version: 1.0
apiVersion: v1
kind: Secret
metadata:
  name: family-ai-butler-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me"
  REDIS_PASSWORD: "change-me"
  NACOS_PASSWORD: "change-me"
  NACOS_AUTH_TOKEN: "change-me-change-me-change-me-change-me"
  NACOS_AUTH_IDENTITY_KEY: "serverIdentity"
  NACOS_AUTH_IDENTITY_VALUE: "security"
  JWT_ACCESS_KEY: "replace-with-base64-access-key"
  JWT_REFRESH_KEY: "replace-with-base64-refresh-key"
  OPENAPI_DOCS_ACCESS_TOKEN: "replace-with-openapi-token"
  AI_QWEN_KEY: "replace-with-your-key"
